language : node_js
node_js  : stable
addons:
  sonarcloud:
    organization: "ramyaganesan-github" # the key of the org you chose at step #3
    token:
      secure: 
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
